import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Header from './Header.jsx';
import Nav from './Nav.jsx';
import Main from './Main.jsx';
import Aside from './Aside.jsx';
import Footer from './Footer.jsx';
import App from './App.js'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <App/>

      <Header/>
      <Nav/>
      <Main/>
      <Aside/>
      <Footer/>

      
    </>
  )
}
